# Generated by Django 3.2.9 on 2021-11-29 17:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=13),
            preserve_default=False,
        ),
    ]
