# Generated by Django 3.2.9 on 2021-12-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20211221_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekcja',
            name='dzien',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='lekcja',
            name='rodzaj',
            field=models.IntegerField(blank=True, choices=[(0, 'Wyk'), (1, 'Lab'), (2, 'Cw')]),
        ),
    ]
