# Generated by Django 3.2.9 on 2021-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20211221_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekcja',
            name='sala',
            field=models.CharField(max_length=50, null=50),
            preserve_default=50,
        ),
    ]
