# Generated by Django 3.2.9 on 2022-01-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_lekcja_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekcja',
            name='dzien',
            field=models.IntegerField(blank=True, choices=[(0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY'), (5, 'SATURDAY'), (6, 'SUNDAY')]),
        ),
    ]
