# Generated by Django 3.2.9 on 2022-01-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20220111_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekcja',
            name='dlugosc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
