# Generated by Django 3.2.9 on 2022-01-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_auto_20220111_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lekcja',
            name='dlugosc',
        ),
    ]
