# Generated by Django 3.2.9 on 2022-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_alter_lekcja_dzien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekcja',
            name='rodzaj',
            field=models.IntegerField(blank=True, choices=[(0, 'Wykład'), (1, 'Laboratorium'), (2, 'Ćwiczenie')]),
        ),
    ]
